#!/bin/sh
# Enable this pre-commit hook by executing the following from the project root directory
# $ ln -s $PWD/scripts/pre-commit .git/hooks/pre-commit
git diff --cached --name-only --diff-filter=ACM | grep -P '\.js$' | xargs jshint
